# Generated by Django 5.2.3 on 2025-06-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beeproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
