# Generated by Django 5.2.3 on 2025-07-02 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoneyTaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taste', models.CharField(choices=[('Akacja', 'Akacjowy'), ('Rzepak', 'Rzepakowy'), ('Spadź', 'Spadziowy'), ('Facelia', 'Faceliowy'), ('Gryka', 'Gryczany'), ('Lipa', 'Lipowy'), ('Malina', 'Malinowy'), ('Imbir', 'Imbir z cytryną'), ('Żurawina', 'Żurawinowy'), ('Porzeczka', 'Porzeczkowy')], default='Akacja', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HoneyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('kremowany', 'Kremowany'), ('naturalny', 'Naturalny'), ('smak', 'Smakowy')], default='naturalny', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HoneyVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(choices=[('50', 'Small - 50ml'), ('500', 'Medium - 400ml'), ('1000', 'Large - 1000ml')], default='1000', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HoneyOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('quantity', models.IntegerField(default=1)),
                ('taste', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='honey.honeytaste')),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='honey.honeytype')),
                ('variant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='honey.honeyvariant')),
            ],
        ),
    ]
