# Generated by Django 5.2.3 on 2025-06-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Honey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Akacja', 'Akacjowy'), ('Rzepak', 'Rzepakowy'), ('Spadź', 'Spadziowy'), ('Facelia', 'Faceliowy'), ('Malina', 'Malinowy'), ('Imbir', 'Imbir z cytryną'), ('Kremowany', 'Kremowany')], default='Akacja', max_length=50)),
                ('size', models.CharField(choices=[('50', 'Small - 50ml'), ('500', 'Medium - 500ml'), ('1000', 'Large - 1000ml')], default='Large', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
            ],
        ),
    ]
