# Generated by Django 5.2.3 on 2025-07-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honeyvariant',
            name='variant',
            field=models.CharField(choices=[('50', 'Small - 50ml'), ('400', 'Medium - 400ml'), ('1000', 'Large - 1000ml')], default='1000', max_length=50),
        ),
    ]
