# Generated by Django 5.2.3 on 2025-06-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('50', 'Small - 50ml'), ('500', 'Medium - 400ml'), ('1000', 'Large - 1000ml')], default='Large', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='honey',
            name='size',
        ),
        migrations.AddField(
            model_name='honey',
            name='size',
            field=models.ManyToManyField(to='honey.size'),
        ),
    ]
