# Generated by Django 5.2.3 on 2025-06-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honey', '0002_size_remove_honey_size_honey_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='honey',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
