# Generated by Django 5.2.3 on 2025-07-10 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honey', '0002_alter_honeyvariant_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honeyoffer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, validators=[django.core.validators.MinValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='honeyoffer',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
