# Generated by Django 5.2.3 on 2025-06-26 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honey', '0003_honey_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='honey',
            name='size',
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(choices=[('50', 'Small - 50ml'), ('500', 'Medium - 400ml'), ('1000', 'Large - 1000ml')], max_length=20),
        ),
        migrations.AddField(
            model_name='honey',
            name='size',
            field=models.ForeignKey(default='1000', on_delete=django.db.models.deletion.CASCADE, to='honey.size'),
        ),
    ]
