# Generated by Django 5.2.3 on 2025-07-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honey', '0003_alter_honeyoffer_price_alter_honeyoffer_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Wosk', 'Wosk pszczeli - 100g'), ('Propolis', 'Propolis 60% - 50ml'), ('Pierzga', 'Pierzga - 300g'), ('Pyłek', 'Pyłek pszczeli - 500g')], default='Pyłek pszczeli - 500g', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
