# Generated by Django 5.2.3 on 2025-06-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honey', '0004_remove_honey_size_alter_size_name_honey_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honey',
            name='size',
            field=models.CharField(choices=[('50', 'Small - 50ml'), ('500', 'Medium - 400ml'), ('1000', 'Large - 1000ml')], default='1000', max_length=50),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
