# Generated by Django 5.2.3 on 2025-06-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honey', '0005_alter_honey_size_delete_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honey',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='honey',
            name='size',
            field=models.CharField(choices=[('50', 'Small - 50ml'), ('500', 'Medium - 400ml'), ('1000', 'Large - 1000ml')], max_length=50),
        ),
        migrations.AlterField(
            model_name='honey',
            name='type',
            field=models.CharField(choices=[('Akacja', 'Akacjowy'), ('Rzepak', 'Rzepakowy'), ('Spadź', 'Spadziowy'), ('Facelia', 'Faceliowy'), ('Malina', 'Malinowy'), ('Imbir', 'Imbir z cytryną'), ('Kremowany', 'Kremowany')], max_length=50),
        ),
    ]
