# Generated by Django 5.2.3 on 2025-07-18 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honey', '0005_alter_beeproduct_price_alter_beeproduct_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beeproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='honeyoffer',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
