# Generated by Django 5.2.3 on 2025-07-14 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honey', '0004_beeproduct'),
        ('shop', '0002_beeproduct_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('honey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='honey.honeyoffer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='honey.beeproduct')),
            ],
        ),
        migrations.DeleteModel(
            name='BeeProduct',
        ),
    ]
