# Generated by Django 5.2.3 on 2025-07-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
